### ISSUE TITLE
Use Windows-provided ICU?

### ISSUE THREAD

**Issue by davidchisnall** [gnustep/tools-windows-msvc#2]
It looks as if Windows has shipped ICU DLLs that provide the C APIs (and, as far as I know, GNUstep doesn't use the C++ ones) since 2017, with the headers in the SDK:

https://docs.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-

It would be great if you could use the system one rather than having to bundle another copy of ICU.  As I recall, ICU is about as big as everything else combined.

**Comment by triplef** [comment]
Oh that’s great, thank you for this info. ICU data alone is about 28 MB, so this would be a nice improvement. I’ll take a look.
