### ISSUE TITLE
module support

### ISSUE THREAD

**Issue by alanflex** [gnustep/tools-windows-msvc#25]
Apologies for my lack of detail, I'm feeling my way here but.... I've done a bit of rudimentary digging but as a mostly-mac-guy trying to get some code building under Windows (where I haven't developed since 2004) I figure I'd just come and ask if anyone had been there before :-)

Currently I need to use

```
#ifdef BUILDING_ON_WINDOWS
#include <Foundation/Foundation.h>
#else
@import Foundation;
#endif
```

in my own code because otherwise my build fails to find the module for Foundation.  I'm assuming that's because the way GNUStep is being built doesn't use a module map or generate a PCM file. (?) 

Is this something that has been tried before?  Am I on the right track at all?  Is it worth trying to investigate further how I would need to modify the clang calls to generate the module information so my own code could just `@import Foundation` and work ?

Thanks in advance for any thoughts or suggestions :-)

Alan

**Comment by triplef** [comment]
Good question. I’m not entirely sure what’s needed here, but can you try adding the `-fmodules` option when building?

**Comment by alanflex** [comment]
I *think* that `-fmodules` means clang will look for modules.  I add that to my code and then it does indeed recognise @import and look for Foundation, but it doesn't find it.  

I think I might try making a modulemap, but my main experience with that is building an apple framework.  I'm not sure how it will work with a DLL.  I'll keep playing, just wanted to see if there was any prior art. :-)

**Comment by triplef** [comment]
Sounds good. Maybe @davidchisnall do you know if it's possible to use the @import module syntax on Windows / with the GNUstep runtime?

**Comment by alanflex** [comment]
initial experiment of just making a module map file for Foundation that includes the umbrella header shows it *is* possible, and did indeed work.... but there were too many "huh. not sure what error means" for me to proceed blindly.
