### ISSUE TITLE
MSYS2: Cannot build a simple Hello World with clang64 environment

### ISSUE THREAD

**Issue by DirectX-Box** [gnustep/tools-windows-msvc#30]
Hello,

I wanted to give GNUstep on Windows a try after finding this repository that seems to replace the old toolchain still shown on the main website; the cross-platform GUI capability is interesting.

I noticed that the "Latest Build" prerelease seems to ship `libs-gui` so it's the one I chose.

Here is the sample Hello World code I am trying to build:

```objc
#import <Foundation/Foundation.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        NSLog(@"Hello, World!");
    }
    return 0;
}
```

This builds successfully when using the VS2022 + `clang-cl` steps:

```bash
# build test.m to produce an object file test.obj
clang-cl -I C:\GNUstep\x64\Release\include -fobjc-runtime=gnustep-2.0 -Xclang -fexceptions -Xclang -fobjc-exceptions -fblocks -DGNUSTEP -DGNUSTEP_WITH_DLL -DGNUSTEP_RUNTIME=1 -D_NONFRAGILE_ABI=1 -D_NATIVE_OBJC_EXCEPTIONS /MDd /Z7 /c test.m

# link object file into executable using the LLD linker
clang-cl test.obj gnustep-base.lib objc.lib dispatch.lib -fuse-ld=lld /MDd /Z7 -o test.exe /link /LIBPATH:C:\GNUstep\x64\Release\lib
```

However, I can't seem to get it working using MSYS2's clang (in the CLANG64 environment):

```bash
$ clang `gnustep-config --objc-flags` -c test.m
In file included from test.m:1:
In file included from C:/GNUstep/x64/Release/include/Foundation/Foundation.h:200:
In file included from C:/GNUstep/x64/Release/include/dispatch/dispatch.h:30:
C:/GNUstep/x64/Release/include/os/generic_win_base.h:31:13: error: typedef redefinition with
      different types ('int' vs '_mode_t' (aka 'unsigned short'))
typedef int mode_t;
            ^
C:/msys64/clang64/include/sys/types.h:77:17: note: previous definition is here
typedef _mode_t mode_t;
                ^
1 error generated.
```

If I comment out the `typedef` from the file, the program compiles successfully.  
However, the linking step that follows fails:

```bash
$ clang `gnustep-config --base-libs` -ldispatch -o test.exe test.o
lld: error: unable to find library -lvcruntime
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Checking `/clang64/lib/` shows that the only library close to that is `libvcruntime140_app.a`.  
After renaming `libvcruntime140_app.a` to `libvcruntime.a`, the linking step works and I get a functional program.

Is a specific MSYS2 configuration normally required? Or did I just mess everything up?  
Or is there just an issue?

**Comment by DirectX-Box** [comment]
Side note: I tried compiling the Calculator app from the `tests-examples` repository but the linking step failed:

```bash
$ clang `gnustep-config --base-libs` -ldispatch -o Calculator.exe *.o
ld.lld: error: undefined symbol: __declspec(dllimport) NSApp
>>> referenced by CalcFace.o:(_i_CalcFace__applicationDidFinishLaunching_)

ld.lld: error: undefined symbol: $_OBJC_CLASS_NSWindow
>>> referenced by CalcFace.o:(.refptr.$_OBJC_CLASS_NSWindow)

ld.lld: error: undefined symbol: $_OBJC_REF_CLASS_NSButton
>>> referenced by CalcFace.o:(.refptr.$_OBJC_REF_CLASS_NSButton)

ld.lld: error: undefined symbol: $_OBJC_REF_CLASS_NSMenu
>>> referenced by CalcFace.o:(.refptr.$_OBJC_REF_CLASS_NSMenu)

ld.lld: error: undefined symbol: $_OBJC_REF_CLASS_NSTextField
>>> referenced by CalcFace.o:(.refptr.$_OBJC_REF_CLASS_NSTextField)

ld.lld: error: undefined symbol: $_OBJC_REF_CLASS_NSWindow
>>> referenced by CalcFace.o:(.refptr.$_OBJC_REF_CLASS_NSWindow)

ld.lld: error: undefined symbol: $_OBJC_REF_CLASS_NSApplication
>>> referenced by main.o:(.refptr.$_OBJC_REF_CLASS_NSApplication)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems more likely for this to simply be because this toolchain is incomplete yet, though.

**Comment by triplef** [comment]
You’ll want to use the plain "MSYS" environment from MSYS2, not CLANG64 or any of the other MSYS2 environments.

The toolchain requires using the standard Windows Clang compiler, and will likely not work with any of the Clang releases offered as MSYS packages (as they contain MinGW-specific Clang patches). I recommend downloading the latest official Clang, e.g. [LLVM-16.0.6-win64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-16.0.6/LLVM-16.0.6-win64.exe) from [LLVM releases](https://github.com/llvm/llvm-project/releases).

**Comment by triplef** [comment]
Thank you for bringing this up though. I’ve now added the following to the readme:

> You also need a standard Windows release of Clang 16 or later, e.g. installed via [Chocolatey](https://community.chocolatey.org/packages/llvm) (choco install llvm) or the [latest official release](https://github.com/llvm/llvm-project/releases/latest) (download "LLVM-x.y.z-win64.exe"). The explanations below expect that Clang is available in your PATH. Note that using Clang from MSYS2/MinGW packages is not supported as they contain MinGW-specific patches.

Please also note that GUI support is so far limited (see #26 for details).
