### ISSUE TITLE
Build NON-headless backend for MSVC

### ISSUE THREAD

**Issue by gcasa** [gnustep/tools-windows-msvc#41]
Currently, the graphical backend for this is not built.  While at Keysight, I did add this, but it seems only the headless backend is here.  The graphical backend and the WinUXTheme should work on MSVC and this should be made available.

NOTE: I believe that because priorities changed when this work was being done, the graphical backend is not here.

**Comment by triplef** [comment]
I believe this is a duplicate of #36, right? In any case would be great if you could add the graphical backend.

**Comment by gcasa** [comment]
It is indeed.  I will work on that over the weekend.

**Comment by gcasa** [comment]
Duplicate of #36
