### ISSUE TITLE
typedef redefinition with different types ('int' vs '_mode_t' (aka 'unsigned short')) on vanilla install

### ISSUE THREAD

**Issue by bamwu** [gnustep/tools-windows-msvc#45]
I'm gettting `typedef redefinition with different types ('int' vs '_mode_t' (aka 'unsigned short'))` on a fairly vanilla install, closely following the instructions in README.md.

This machine (Windows 10 Pro 22H2 on x64) already had VS2019 (Community 16.11.27) and MSYS2 installed. (I won't be using VS2019 for GNUstep projects, but it's worth noting that it's there)

I installed the latest clang using winget -- _as per README.md_ ...

```
$ clang --version
clang version 18.1.5
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/mingw64/bin
```

I downloaded and installed GNUstep `2023-12-28` Debug and Release builds and installed them both at `C:\GNUstep` -- such that I end up with `C:\GNUstep\x64\Debug\...` and `C:\GNUstep\x64\Release\...` -- _as per README.md_ ...

Here's the source file -- _copy/pasted from README.md_ ...

```
#include <Foundation/Foundation.h>
int main(int argc, char *argv[])
{
    NSLog(@"Hello Objective-C");
    return 0;
}
```

These same steps  -- _copy/pasted from README.md_ -- produce the same error in all of the provided MSYS2 shell environments ...

```
me@MYPC MSYS ~
$ whereis clang
clang: /mingw64/bin/clang.exe

me@MYPC MSYS ~
$ export PATH="$PATH:/c/GNUstep/x64/Debug/bin/"

me@MYPC MSYS ~
$ cd /c/Users/me/Desktop/GSTEST/

me@MYPC MSYS /c/Users/me/Desktop/GSTEST
$ clang `gnustep-config --objc-flags` -c test.m
In file included from test.m:1:
In file included from C:/GNUstep/x64/Debug/include/Foundation/Foundation.h:200:
In file included from C:/GNUstep/x64/Debug/include/dispatch/dispatch.h:30:
C:/GNUstep/x64/Debug/include/os/generic_win_base.h:31:13: error: typedef redefinition with different
      types ('int' vs '_mode_t' (aka 'unsigned short'))
   31 | typedef int mode_t;
      |             ^
C:/msys64/mingw64/include/sys/types.h:77:17: note: previous definition is here
   77 | typedef _mode_t mode_t;
      |                 ^
1 error generated.
```

**Comment by bamwu** [comment]
Windows 10 Pro 22H2
VS2019 (Community) 16.11.27

**Comment by triplef** [comment]
It looks like your shell is set up with MSYS2’s "MINGW64" environment and it’s picking up MinGW Clang and headers from that environment. For using GNUstep please use the plain "MSYS" environment, i.e. the first one [listed here](https://www.msys2.org/docs/environments/) and then load the Visual Studio environment inside it (e.g. using vcvarsall.bat).
