### ISSUE TITLE
Anyone able to get this work in VS Code or another IDE?

### ISSUE THREAD

**Issue by SeymourNickelson** [gnustep/tools-windows-msvc#50]
This project is awesome! This isn't really an issue but a _question_ (I apologize if this isn't the place to ask) but...

I was wondering if anyone has gotten this to work in Visual Studio Code? I tried installing some extensions that support Objective-C but could not figure out how to get VSCode to find the GNUStep Foundation headers.  

It'd be awesome to quickly execute Objective-C from VSCode on Windows. Also wondering if anyone knows of an IDE on Windows with better ObjC support than Visual Studio (code completion, etc.).

Thanks!

**Comment by triplef** [comment]
Have you tried following the steps from the readme [here](https://github.com/gnustep/tools-windows-msvc?tab=readme-ov-file#using-the-toolchain-in-visual-studio)?

**Comment by SeymourNickelson** [comment]
Thanks for responding! Indeed I did and running works from Visual Studio which is awesome. But there is no Objective-C code completion so editing Objective-C from Visual Studio is quite tedious (no different than coding in TextEdit or Notepad). I wasn't able to find a Visual Studio extension for Objective-C. 

Visual Studio Code has pretty decent Objective-C completion on Mac with an extension, so I was wondering if anyone successfully integrated the GNUStep toolchain in VSCode rather than Visual Studio. I experimented editing the Objective-C entry in the code-runner.executorMap in VSCode's settings.json but have so far been unsuccessful at getting Objective-C to run with GNUStep.

**Comment by triplef** [comment]
Ah I see, thanks for clarifying. I’m not aware of a way to have code completion for ObjC code in VS.

We’re using the project with Qt Creator, which somewhat works with code completion but obviously only makes sense if you’re using Qt. Using VS Code sounds like the right approach though. If you can convert your project to CMake you should be able to open it in VS Code. Maybe it’s also possible to open VS projects in VS Code.

**Comment by arctic-marmoset** [comment]
My usual go-to combo for C/C++/ObjC on VSCode is [CMake](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools) and [clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd). CMake can generate a `compile_commands.json` for clangd to read to understand include paths, etc.

But if you're just looking to get something up and running quickly, without having to write a CMakeLists.txt, then you can just use clangd and [manually write a `compile_flags.txt`](https://clangd.llvm.org/installation#compile_flagstxt) and place it in your project root.

Example `compile_flags.txt`:
```
-xobjective-c
-DGNUSTEP
-DGNUSTEP_WITH_DLL
-DGNUSTEP_RUNTIME=1
-D_NONFRAGILE_ABI=1
-D_NATIVE_OBJC_EXCEPTIONS
-fblocks
-fexceptions
-fmodules
-fobjc-arc
-fobjc-exceptions
-fobjc-runtime=gnustep-2.0
-isystem
/path/to/GNUstep/include
```

**Comment by hmelder** [comment]
> I was wondering if anyone has gotten this to work in Visual Studio Code? I tried installing some extensions that support Objective-C but could not figure out how to get VSCode to find the GNUStep Foundation headers.

Yep using `compile_commands.json` generated by CMake or using https://github.com/rizsotto/Bear.
