### ISSUE TITLE
Objc.dll Microsoft C++ Exception when using the DLL generated by MSVC

### ISSUE THREAD

**Issue by abhi-varma202** [gnustep/tools-windows-msvc#9]
Hi, I have created a DLL which is used by an application. I have created this DLL using the MSVC toolchain and my app is successfully able to load this DLL but for some reason its throwing an exception insider objc.dll 

```
Exception thrown at 0x00007FFCFE843B6A (objc.dll) in xyz.exe: 0xE06D7363: Microsoft C++ Exception (parameters: 0x0000000019930520, 0x0000000007CDFC18, 0x0000000007CDFC20, 0x0000000007CDFC37).
```

Is there a way to find out what the exception is exactly?

**Comment by triplef** [comment]
Did you build all your DLLs using matching /MD or /MDd flags?

Otherwise you should be able to debug this by launching the exe in Visual Studio ("Open a project or solution"), and adding the `C:\GNUstep\x64\Debug\bin` to your symbol file locations in the VS settings, so it can find the .pdb files.
